### ISSUE TITLE
[+] Running checks...

### ISSUE THREAD

**Issue by Kalliingi** [trustee-wallet/trusteeWalletAssets#2]
[+] Running checks...

-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CEUR, CELO_TOKEN]: displayed as: cEUR
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [CUSD, CELO_TOKEN]: displayed as: cUSD
-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range
-  ⚠️  [MATIC.MATIC, COIN]: displayed as: MATIC.MATIC
-  ⚠️  [NEAR, COIN]: minWithdrawal 0.01 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [RENBTC, ERC20]: displayed as: renBTC

__Originally posted by @blockchain-concourse-platform in https://github.com/blockchain/coin-definitions/pull/71#issuecomment-1068199245__

**Comment by Turtus** [comment]
bsv - has logo
ceur - correct 
clout/deso - we dont have such coin (both no clout no deso)
cusd - correct
dgld - no coin
matic - correct
near - no coin
pax - correct
renbtc - correct
